;NHAN 1 BYTE TU MAY TINH VA XUAT TRO LAI TERMINAL
;BAT LED P1.1 KHI SW (P1.0) DUOC NHAN VA TAT LED KHI SW NHA
;**********************************************************

ORG 0000H
    JMP MAIN  
ORG 0023H         ;DIA CHI VECTOR NGAT SERIAL PORT
    JMP SP_ISR    ;NHAY TOI CHUONG TRINH NGAT SERIAL PORT
ORG 0030H
MAIN:
    CALL SERIAL_INIT
    MOV IE, #90H       ;CHO PHEP NGAT TOAN CUC, SERIAL PORT
LOOP:
    JB P1.0, CONT1
    CLR P1.1
CONT1:
    JNB P1.0, CONT2
    SETB P1.1
CONT2:
    SJMP LOOP
;END MAIN

;KHOI TAO CONG NOI TIEP ***********************************
SERIAL_INIT:
    MOV A, PCON
    SETB ACC.7
    MOV PCON, A       ;3 LENH TREN SET BIT SMOD LEN 1

    MOV SCON, #52H    ;CONG NOI TIEP, CHE DO 1, THU - PHAT
    MOV TMOD, #20H    ;TIMER1, CHE DO 2
    MOV TH1, #-3      ;TRI NAP LAI CHO 19200 BAUD
    SETB TR1          ;CHO TIMER1 CHAY    
RET
;END SERIAL_INIT ******************************************

SP_ISR:           ;CHUONG TRINH NGAT SP
    JNB RI, SKIP
    CLR RI
    MOV A, SBUF
    JNB TI, $
    CLR TI
    MOV SBUF, A
SKIP:
RETI
;END SP_ISR

END