ORG 0000H
    LJMP MAIN
ORG 0003H
    LJMP BTN_ISR
ORG 0013H
    LJMP COUNT_ISR
ORG 0030H
MAIN:
    MOV IE, #81H    ; CHI KHOI DONG NGAT NGOAI 0 CHO NUT NHAN
    MOV R0, #0
    CLR F0          ; DUNG F0 DE KIEM TRA TRANG THAI KHI NHAN NUT

LOOP:
    MOV A, R0
    MOV B, #10
    DIV AB
    ANL A, #0FH
    SWAP A
    ADD A, B
    MOV P1, A
    SJMP LOOP

BTN_ISR:
    JNB P3.2, $     ; CHONG RUNG
    JB F0, CHECK_OUT
    INC R0
    INC R0
    INC R0
    SETB IE.2       ; KICH HOAT NGAT NGOAI 1 DE KHOI DONG BO DEM
    CPL F0          ; CHUYEN TRANG THAI
    RETI
CHECK_OUT:
    JNB IE.2, RESET
    CLR IE.2
    RETI
RESET:
    MOV R0, #0
    CPL F0          ; CHUYEN TRANG THAI VE BAN DAU
    RETI

COUNT_ISR:
    JNB P3.3, $     ; CHONG RUNG
    INC R0
    INC R0
    INC R0
    RETI

END