ORG 2000H
DEF:
    HANG_Y EQU 2            ;VI TRI HANG CAN SANG LED: CHON 0-7
    Y_DATA EQU 02AH         ;TRANG THAI LED TREN HANG Y: CHON 0H-FFH

MAIN:
    MOV R1, #HANG_Y
    MOV R0, #Y_DATA

;HIEN THI DATA LEN HANG THU Y CUA LED MATRIX (MSB BEN TRAI LED MATRIX)
DISPLAY:
    MOV B, R1
    MOV A, #0FEH
SHIFTLOOP:
    RL A
    DJNZ B, SHIFTLOOP

    MOV DPTR, #0A000H
    MOVX @DPTR, A
    MOV A, R0
    MOV DPTR, #8000H
    MOVX @DPTR, A
;END DISPLAY
END